import ReactMarkdown from "react-markdown"

export default function MistralRecipe(prop) {
/**  
 * Mistrals recipe
 * prop:
 *  - recipe: Recipe generated by Mistral
**/
    return (
        <section className="suggested-recipe-container">
            <h2>Chef Recommends:</h2>
            <ReactMarkdown children={prop.recipe} />
        </section>
    );
}